# Generated by Django 5.2.1 on 2025-06-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
            },
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='related_order_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='movement_type',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='units_in_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='app.product'),
        ),
    ]
