# Generated by Django 5.2.1 on 2025-07-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_branch_options_purchaseorder_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.storelocation'),
            preserve_default=False,
        ),
    ]
