# Generated by Django 5.2.1 on 2025-07-03 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_purchaseorder_store'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='app.branch'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='app.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'store', 'branch')},
        ),
    ]
