# Generated by Django 5.2.1 on 2025-07-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_inventory_unique_together_inventory_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'store')},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='branch',
        ),
    ]
