# Generated by Django 5.2.1 on 2025-07-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='branch',
        ),
    ]
