# Generated by Django 5.2.1 on 2025-07-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_purchaseorder_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='branch',
        ),
    ]
