# Generated by Django 5.2.1 on 2025-07-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_stockmovement_transaction_type'),
        ('app', '0011_remove_stocktransfer_branch_and_more'),
    ]

    operations = [
    ]
