# Generated by Django 5.2.1 on 2025-07-10 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20250708_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TransferRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.transferrequest')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productunitprice')),
            ],
            options={
                'unique_together': {('transfer_request', 'product')},
            },
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='transfer_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_transfer_items', to='app.transferrequestitem'),
        ),
    ]
