# Generated by Django 5.2.1 on 2025-07-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20250708_0933'),
        ('app', '0013_alter_transferrequest_approved_date_and_more'),
    ]

    operations = [
    ]
