# Generated by Django 5.2.1 on 2025-07-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250713_0859'),
        ('app', '0014_merge_20250713_0907'),
    ]

    operations = [
    ]
