# Generated by Django 5.2.1 on 2025-07-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250712_0440'),
        ('app', '0016_department_remove_sales_branch_and_more'),
    ]

    operations = [
    ]
