# Generated by Django 5.2.1 on 2025-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20250718_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='receipt_no',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
