# Generated by Django 5.2.1 on 2025-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_expense_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='currency',
            field=models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('KSH', 'Kenyan Shilling')], default='UGX', max_length=50),
        ),
    ]
