# Generated by Django 5.2.1 on 2025-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_organizationsetting_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
