# Generated by Django 5.2.1 on 2025-08-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sales_amount_paid_sales_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
