# Generated by Django 5.2.1 on 2025-08-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_paymentmethod_alter_inventorybatch_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.paymentmethod'),
            preserve_default=False,
        ),
    ]
