# Generated by Django 5.2.1 on 2025-08-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_sales_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='dailycashsummary',
            name='calculated_balance',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailycashsummary',
            name='closing_balance',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailycashsummary',
            name='opening_balance',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.paymentmethod'),
            preserve_default=False,
        ),
    ]
