# Generated by Django 5.2.1 on 2025-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_employee_unique_together_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
