# Generated by Django 5.2.1 on 2025-08-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_product_brand_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16),
        ),
    ]
