# Generated by Django 5.2.1 on 2025-08-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_stocktransferitem_units_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerledger',
            options={'ordering': ['-date'], 'verbose_name': 'Customer Ledger Entry', 'verbose_name_plural': 'Customer Ledger Entries'},
        ),
    ]
