# Generated by Django 5.2.1 on 2025-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_stockadjustment_stockadjustmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
