# Generated by Django 5.2.1 on 2025-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_sales_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
