# Generated by Django 5.2.1 on 2025-09-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_paymentmethod_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
