# Generated by Django 5.2.1 on 2025-09-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_inventorybatch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequestitem',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unitofmeasure'),
        ),
    ]
