# Generated by Django 5.2.1 on 2025-09-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_stocktransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='from_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='app.storelocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='app.storelocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.unitofmeasure'),
        ),
    ]
