# Generated by Django 5.2.1 on 2025-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_stocktransfer_from_store_stocktransfer_to_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
