# Generated by Django 5.2.1 on 2025-09-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_transferrequest_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_transfer_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
