# Generated by Django 5.2.1 on 2025-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_sales_recorded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid_code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
