# Generated by Django 5.2.1 on 2025-10-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_remove_product_uuid_code_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='app.transferrequest'),
        ),
    ]
