# Generated by Django 5.2.1 on 2025-12-02 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_stocktransfer_transfer_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='unit_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StockAdjustmentItem',
        ),
    ]
