# Generated by Django 5.2.1 on 2025-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_stocktransfer_transfer_request'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='stockadjustmentitem',
        #     name='unit_cost',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
    ]
