# Generated by Django 5.2.1 on 2025-11-22 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_stockadjustmentitem_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-transfer_date']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'store'], name='app_invento_product_fd92a3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['store', 'product'], name='app_invento_store_i_65d9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['last_updated'], name='app_invento_last_up_633be5_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_store', 'status'], name='app_stocktr_from_st_c6ddd0_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'from_store'], name='app_stocktr_status_e75142_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferitem',
            index=models.Index(fields=['product', 'stock_transfer'], name='app_stocktr_product_8a3a43_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferitem',
            index=models.Index(fields=['stock_transfer', 'product'], name='app_stocktr_stock_t_f08475_idx'),
        ),
    ]
