# Generated by Django 5.2.1 on 2025-12-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_stockadjustment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockadjustment',
            unique_together={('reference', 'product', 'unit')},
        ),
    ]
