# Generated by Django 5.2.1 on 2025-11-24 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_stocktransfer_options_inventory_last_updated_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_staff', models.BooleanField(default=False, help_text='Users with this role can access the admin site')),
                ('is_active', models.BooleanField(default=True, help_text='Users with this role will be active by default')),
                ('is_superuser', models.BooleanField(default=False, help_text='Users with this role will have all permissions')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: Department this role is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='app.department')),
                ('designation', models.ForeignKey(blank=True, help_text='Optional: Designation this role is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='app.designation')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_system_role', models.BooleanField(default=False)),
                ('department_name', models.CharField(blank=True, default='', max_length=100)),
                ('designation_title', models.CharField(blank=True, default='', max_length=100)),
                ('module_count', models.IntegerField(default=0)),
                ('user_count', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_deletions', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='app.role')),
            ],
            options={
                'verbose_name': 'Role Deletion Log',
                'verbose_name_plural': 'Role Deletion Logs',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='Date when role was assigned')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('access_modules', models.JSONField(blank=True, default=list, help_text='List of module IDs the user has access to')),
                ('password_created_by', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(blank=True, help_text='Linked employee record (if user is an employee)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='app.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='app.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.PositiveIntegerField()),
                ('module_name', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.role')),
            ],
            options={
                'verbose_name': 'Role Module',
                'verbose_name_plural': 'Role Modules',
                'ordering': ['module_id'],
                'unique_together': {('role', 'module_id')},
            },
        ),
    ]
