# Generated by Django 5.2.1 on 2025-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_stockadjustment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
