# Generated by Django 5.2.1 on 2025-11-24 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_role_roledeletionlog_userprofile_rolemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Multiple roles assigned to this user', related_name='assigned_profiles', to='app.role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use roles M2M field instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_user_profiles', to='app.role'),
        ),
    ]
