# Generated by Django 5.2.1 on 2025-11-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_rbac2_multi_role_upgrade'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='transferrequest',
        #     name='department',
        #     field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='app.department'),
        # ),
    ]
