# Generated by Django 5.2.1 on 2025-11-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_add_priority_required_date'),
        ('app', '0061_transferrequest_department'),
    ]

    operations = [
    ]
