# Generated by Django 5.2.1 on 2025-12-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_merge_20251125_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='app.department'),
        ),
        # migrations.AlterField(
        #     model_name='stockadjustmentitem',
        #     name='unit_cost',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
    ]
