# Generated by Django 5.2.1 on 2025-12-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_stockadjustment_reason'),
        ('app', '0063_transferrequest_department_and_more'),
    ]

    operations = [
    ]
