# Generated by Django 5.2.1 on 2026-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_sales_amount_paid_alter_sales_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount_paid',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount_received',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='change',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
