# Generated by Django 5.2.1 on 2026-01-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_sales_options_sales_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['is_cancelled', 'status'], name='app_sales_is_canc_b72f02_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['receipt_no'], name='app_sales_receipt_08bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['order', 'is_cancelled'], name='app_salesit_order_i_c885c9_idx'),
        ),
    ]
