# Generated by Django 5.2.1 on 2026-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_sales_cancellation_reason_sales_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequestitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
