# Generated by Django 5.2.1 on 2026-01-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_transferrequestitem_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunitprice',
            options={'ordering': ['conversion_factor']},
        ),
        migrations.AlterUniqueTogether(
            name='stocktransferitem',
            unique_together={('stock_transfer', 'product', 'units')},
        ),
        migrations.AlterUniqueTogether(
            name='transferrequestitem',
            unique_together={('transfer_request', 'product', 'units')},
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='base_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='original_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='transferrequestitem',
            name='base_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='productunitprice',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
