# Generated by Django 5.2.1 on 2026-01-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_productunitprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatch',
            options={'ordering': ['expiry_date', 'received_date'], 'verbose_name': 'Inventory Batch (Base Units)', 'verbose_name_plural': 'Inventory Batches (Base Units)'},
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='base_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='base_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='ui_quantity_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='ui_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_ui_units', to='app.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='ui_quantity_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='ui_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_item_ui_units', to='app.unitofmeasure'),
        ),
    ]
