# Generated by Django 5.2.1 on 2026-01-17 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_inventorybatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.AlterModelOptions(
            name='transferrequestitem',
            options={'ordering': ['product__name'], 'verbose_name': 'Transfer Request Item', 'verbose_name_plural': 'Transfer Request Items'},
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'from_store'], name='app_transfe_status_a57575_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'to_store'], name='app_transfe_status_64663b_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['priority', 'status'], name='app_transfe_priorit_07486f_idx'),
        ),
    ]
