# Generated by Django 5.2.1 on 2026-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_stocktransfer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunitprice',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=0, default=1.0, max_digits=10),
        ),
    ]
