# Generated by Django 5.2.1 on 2026-01-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_productunitprice_conversion_factor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocktransfer',
            name='app_stocktr_from_st_c6ddd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransfer',
            name='app_stocktr_status_e75142_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransferitem',
            name='app_stocktr_product_8a3a43_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocktransferitem',
            name='app_stocktr_stock_t_f08475_idx',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='transfer_request_item',
        ),
    ]
