# Generated by Django 5.2.1 on 2026-01-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_remove_stocktransfer_app_stocktr_from_st_c6ddd0_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={},
        ),
    ]
