# Generated by Django 5.2.1 on 2026-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_stocktransfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='fulfilled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
