# Generated by Django 5.2.1 on 2026-01-19 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_transferrequest_fulfilled_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='inventory_changes_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'from_store'], name='app_stocktr_status_e75142_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'to_store'], name='app_stocktr_status_8ccd35_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['created_at'], name='app_stocktr_created_fe0dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['inventory_changes_applied'], name='app_stocktr_invento_dc321b_idx'),
        ),
    ]
