# Generated by Django 5.2.1 on 2026-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_automotive_product_compatible_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.automotive', verbose_name='Compatibility'),
        ),
    ]