# Generated by Django 5.2.1 on 2026-04-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_alter_product_compatible_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
