# Generated by Django 5.2.1 on 2026-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_remove_product_compatible_vehicles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.automotive', verbose_name='Compatibility'),
        ),
    ]
