# Generated by Django 5.2.1 on 2026-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_migrate_country_and_currency_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='country',
            field=models.CharField(choices=[('Uganda', 'Uganda'), ('Kenya', 'Kenya'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('South Sudan', 'South Sudan'), ('DRC', 'DR Congo'), ('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('South Africa', 'South Africa'), ('Other', 'Other')], default='Uganda', max_length=40),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='currency',
            field=models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='UGX', max_length=50),
        ),
    ]
