# Generated by Django 5.2.1 on 2026-04-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_organizationsetting_country_and_more'),
        ('app', '0091_notification'),
    ]

    operations = [
    ]
