# Generated by Django 5.2.1 on 2025-12-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_stockadjustment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockadjustment',
            unique_together=set(),
        ),
    ]
